#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: waveyard desktop setup — Ubuntu 24.04.4 + ROCm 7.2.4 + PyTorch on an
# RX 9070 XT. Run on the freshly installed Ubuntu:
#     bash scripts/desktop-rocm-setup.sh
# Several stages end in a reboot. Re-run the script after each reboot; stages
# already done are detected and skipped. Facts are recorded in ~/.waveyard-desktop.env
# so the wayfinder ticket can be resolved from them.
# Sources for every command: ROCm 7.2.4 quick start
#   https://rocm.docs.amd.com/projects/install-on-linux/en/docs-7.2.4/install/quick-start.html
# and post-install
#   https://rocm.docs.amd.com/projects/install-on-linux/en/docs-7.2.1/install/post-install.html
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="$HOME/.waveyard-desktop.env"

ROCM_VER="7.2.4"
AMDGPU_DEB="amdgpu-install_7.2.4.70204-1_all.deb"
AMDGPU_URL="https://repo.radeon.com/amdgpu-install/${ROCM_VER}/ubuntu/noble/${AMDGPU_DEB}"
TORCH_INDEX="https://download.pytorch.org/whl/rocm7.2"
REPO_URL="https://github.com/brwier/waveyard.git"
REPO_DIR="$HOME/projects/waveyard"

reboot_and_rerun() {
  printf '\n'
  warn "A reboot is required before the next stage."
  say  "Reboot now, log back in, and run this script again; finished stages are skipped."
  if confirm "Reboot now?"; then sudo reboot; fi
  exit 0
}

banner "waveyard desktop setup: ROCm ${ROCM_VER} + PyTorch on the RX 9070 XT"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Preflight: OS, kernel, GPU, network"
OS_DESC=$(. /etc/os-release && echo "$PRETTY_NAME")
KERNEL=$(uname -r)
say "OS:     $OS_DESC"
say "Kernel: $KERNEL"
if [[ "$OS_DESC" != *"24.04"* ]]; then warn "Expected Ubuntu 24.04.x; ROCm ${ROCM_VER} supports 24.04.4 with kernel 6.8 GA."; fi
if [[ "$KERNEL" == 6.8.* ]]; then note "Kernel 6.8 is the 24.04 GA kernel: supported by ROCm ${ROCM_VER}."
elif [[ "$KERNEL" == 6.17.* ]]; then note "Kernel 6.17 is the 24.04.4 HWE kernel (what the 24.04.4 desktop ISO installs): supported by ROCm ${ROCM_VER}."
else warn "Kernel is neither 6.8 (GA) nor 6.17 (HWE). ROCm ${ROCM_VER} lists only those two for 24.04.4. The wizard will skip AMD's DKMS driver and rely on this kernel's in-tree amdgpu, which supports RDNA4 from 6.13 onward."; fi
# Command substitution, not `cmd | grep -q`: under pipefail a quitting grep -q
# gives the producer SIGPIPE and the test reads as "not found".
# Class 03xx is any display controller; vendor 1002 is AMD. An old pci.ids
# shows a new card as "Device [1002:7550]", so match on ids, not names.
GPU_LINE=$(lspci -nn -d 1002: 2>/dev/null | grep -E '\[03[0-9a-f]{2}\]' | head -1 || true)
if [[ -n "$GPU_LINE" ]]; then
  say "GPU:    ${GPU_LINE#*: }"
else
  warn "No AMD GPU found by lspci. Stop here and check the card is seated and the display cable is on it."
  exit 1
fi
if ! ping -c1 -W3 repo.radeon.com >/dev/null 2>&1; then warn "repo.radeon.com is not reachable; connect to the network first."; exit 1; fi
write_env OS "$OS_DESC"
write_env KERNEL "$KERNEL"
pause

# ── 2. System update ──────────────────────────────────────────────────────
stage "System update"
say "Bring Ubuntu fully up to date before adding AMD's repository."
if confirm "Run: sudo apt update && sudo apt full-upgrade -y ?"; then
  sudo apt update && sudo apt full-upgrade -y
  if [[ -f /var/run/reboot-required ]]; then reboot_and_rerun; fi
else
  note "skipped"
fi

# ── 3. Register AMD's repository ──────────────────────────────────────────
stage "Register AMD's ROCm ${ROCM_VER} repository"
if dpkg -s amdgpu-install >/dev/null 2>&1; then
  note "amdgpu-install is already installed: $(dpkg -s amdgpu-install | awk '/^Version/{print $2}'); skipping"
else
  say "This downloads AMD's small repository-registration package and installs it."
  say "URL: $AMDGPU_URL"
  if confirm "Download and install ${AMDGPU_DEB}?"; then
    ( cd /tmp && wget -q --show-progress "$AMDGPU_URL" && sudo apt install -y "./${AMDGPU_DEB}" )
    sudo apt update
  else
    warn "Cannot continue without the repository."; exit 1
  fi
fi

# ── 4. Kernel driver (DKMS) ───────────────────────────────────────────────
stage "AMD kernel driver (amdgpu-dkms)"
if dpkg -s amdgpu-dkms >/dev/null 2>&1 && [[ -d /sys/module/amdgpu ]]; then
  note "amdgpu-dkms installed and the amdgpu module is loaded; skipping"
elif [[ "$KERNEL" != 6.8.* && "$KERNEL" != 6.17.* && -d /sys/module/amdgpu ]]; then
  note "Kernel $KERNEL is newer than ROCm ${ROCM_VER}'s DKMS driver targets and its in-tree amdgpu is already loaded."
  say "Skipping amdgpu-dkms: it is built against 6.8 and 6.17 and would likely fail to compile here."
  say "ROCm userspace runs on the in-tree driver. If 'Verify ROCm sees the GPU' fails later, the"
  say "fallback is: sudo apt install linux-generic, reboot into the 6.8 kernel, and rerun this wizard."
else
  say "AMD's quick start installs its own kernel module via DKMS. Secure Boot is OFF on this"
  say "machine (verified from Windows), so no module signing is needed."
  say "Commands:"
  say "  sudo apt install linux-headers-\$(uname -r) linux-modules-extra-\$(uname -r)"
  say "  sudo apt install amdgpu-dkms"
  if confirm "Install headers and amdgpu-dkms?"; then
    sudo apt install -y "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
    sudo apt install -y amdgpu-dkms
    say "DKMS status: $(dkms status 2>/dev/null | grep -i amdgpu || echo 'unknown')"
    reboot_and_rerun
  else
    warn "Cannot continue without the driver."; exit 1
  fi
fi

# ── 5. ROCm userspace ─────────────────────────────────────────────────────
stage "Install ROCm ${ROCM_VER}"
if dpkg -s rocm >/dev/null 2>&1; then
  note "rocm meta-package already installed; skipping install"
else
  say "Installs the ROCm stack (several GB) and adds you to the render and video groups."
  say "Commands:"
  say "  sudo apt install python3-setuptools python3-wheel"
  say "  sudo usermod -a -G render,video \$LOGNAME"
  say "  sudo apt install rocm"
  if confirm "Install ROCm now?"; then
    sudo apt install -y python3-setuptools python3-wheel
    sudo usermod -a -G render,video "$LOGNAME"
    sudo apt install -y rocm
  else
    warn "Cannot continue without ROCm."; exit 1
  fi
fi
if [[ ! -f /etc/ld.so.conf.d/rocm.conf ]]; then
  say "Registering /opt/rocm libraries with the dynamic linker (AMD post-install step)."
  printf '/opt/rocm/lib\n/opt/rocm/lib64\n' | sudo tee /etc/ld.so.conf.d/rocm.conf >/dev/null
  sudo ldconfig
fi
# `id -nG` with no name reports the running session's groups; with a name it
# reads the system database, which already lists groups usermod just added.
USER_GROUPS=" $(id -nG) "
if [[ "$USER_GROUPS" != *" render "* || "$USER_GROUPS" != *" video "* ]]; then
  warn "Your login session does not yet carry the render/video groups (they apply at next login)."
  reboot_and_rerun
fi

# ── 6. Verify ROCm ────────────────────────────────────────────────────────
stage "Verify ROCm sees the GPU"
export PATH="$PATH:/opt/rocm/bin"
if ! command -v rocminfo >/dev/null 2>&1; then warn "rocminfo not found on PATH; is /opt/rocm/bin present?"; exit 1; fi
# `|| true` on each: under set -e a pipeline whose grep finds nothing would
# otherwise exit the script silently before the warning below is printed.
ROCMINFO_OUT=$(timeout 60 rocminfo 2>&1) && ROCMINFO_RC=0 || ROCMINFO_RC=$?
GPU_NAME=$(printf '%s\n' "$ROCMINFO_OUT" | grep -i 'Marketing Name' | grep -vi 'ryzen\|cpu' | head -1 | sed 's/.*:\s*//' || true)
GFX=$(printf '%s\n' "$ROCMINFO_OUT" | grep -io 'gfx[0-9a-f]*' | sort -u | grep -v gfx000 | head -1 || true)
ROCM_INSTALLED=$(dpkg -s rocm-core 2>/dev/null | awk '/^Version/{print $2}' || true)
say "rocminfo GPU:   ${GPU_NAME:-NOT FOUND}"
say "gfx target:     ${GFX:-NOT FOUND}"
say "rocm-core:      ${ROCM_INSTALLED:-unknown}"
say "amd-smi:        $(amd-smi version 2>/dev/null | head -1 || echo 'amd-smi not available')"
if [[ -z "$GPU_NAME" ]]; then
  warn "ROCm does not see the GPU. Diagnostics (paste these to your agent):"
  say "rocminfo exit code: $ROCMINFO_RC (124 means it hung for 60 s)"
  say "rocminfo output, first 15 lines:"
  printf '%s\n' "$ROCMINFO_OUT" | head -15 | sed 's/^/    /'
  say "groups:  $(id -nG)"
  say "/dev/kfd: $(ls -l /dev/kfd 2>&1)"
  say "kernel messages mentioning amdgpu or kfd, last 15:"
  (sudo dmesg 2>/dev/null || true) | grep -iE 'amdgpu|kfd' | tail -15 | sed 's/^/    /'
  say "AMD's FAQ: check 'grep amdgpu /etc/modprobe.d/*' for a denylist. If the in-tree driver on"
  say "kernel $KERNEL does not expose /dev/kfd, the fallback is: sudo apt install linux-generic,"
  say "reboot into the 6.8 kernel, and rerun this wizard so it installs amdgpu-dkms."
  exit 1
fi
write_env GPU_NAME "$GPU_NAME"
write_env GFX_TARGET "$GFX"
write_env ROCM_VERSION "$ROCM_INSTALLED"
pause

# ── 7. Python toolchain and waveyard checkout ─────────────────────────────
stage "uv, Python 3.12, waveyard checkout, PyTorch for ROCm"
if ! command -v uv >/dev/null 2>&1 && [[ ! -x "$HOME/.local/bin/uv" ]]; then
  say "Installing uv (Astral's Python manager) with its official installer."
  if confirm "Run the uv installer (curl -LsSf https://astral.sh/uv/install.sh | sh)?"; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
  else
    warn "Cannot continue without uv."; exit 1
  fi
fi
export PATH="$HOME/.local/bin:$PATH"
uv python install 3.12
if ! command -v git >/dev/null 2>&1; then sudo apt install -y git; fi
if [[ ! -d "$REPO_DIR/.git" ]]; then
  say "Cloning waveyard into $REPO_DIR"
  mkdir -p "$(dirname "$REPO_DIR")"
  git clone "$REPO_URL" "$REPO_DIR"
else
  note "waveyard already cloned at $REPO_DIR"
fi
cd "$REPO_DIR"
[[ -d .venv ]] || uv venv --python 3.12
say "Installing PyTorch from the ROCm 7.2 wheel index (large download, ~ a few GB):"
say "  uv pip install torch --index-url $TORCH_INDEX"
if confirm "Install torch now?"; then
  uv pip install torch --index-url "$TORCH_INDEX"
else
  warn "Skipping torch; the smoke test will fail."
fi

# ── 8. Smoke test and record facts ────────────────────────────────────────
stage "Smoke test: PyTorch sees the GPU"
cd "$REPO_DIR"
RESULT=$(uv run --no-project python - <<'PY' 2>&1 || true
import torch
ok = torch.cuda.is_available()
name = torch.cuda.get_device_name(0) if ok else "none"
print(f"torch={torch.__version__} hip={getattr(torch.version, 'hip', None)} available={ok} device={name}")
if ok:
    a = torch.randn(4096, 4096, device="cuda"); b = a @ a
    torch.cuda.synchronize(); print("matmul ok")
PY
)
printf '  %s\n' "$RESULT"
if [[ "$RESULT" == *"available=True"* ]]; then
  TORCH_LINE=$(printf '%s\n' "$RESULT" | grep '^torch=')
  write_env TORCH "$TORCH_LINE"
  write_env SETUP_DATE "$(date -I)"
  say ""
  say "Paste the following into the wayfinder ticket as its resolution:"
  say "------------------------------------------------------------"
  cat "$ENV_FILE"
  say "------------------------------------------------------------"
else
  warn "PyTorch does not see the GPU. Check: groups (id -nG should list render video), rocminfo, and that torch came from $TORCH_INDEX."
  SKIPPED+=("PyTorch smoke test (see warning above)")
fi

finish
